version: '3.8'

services:

  mongo:
    image: mongo #最新版 or tag:: vd mongo:windowsservercore-ltsc2022
    container-name: mongo-container #追加：ここから
    port:                           #
      - 27018:27017                 #ここまで
    volumes:
      - './mongodb:/data/db' #backup khi sever bi sap
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc123 #set

  mongo-express:
    image: mongo-express
    container-name: mongo-express-container #追加
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Abc123 #set
      ME_CONFIG_MONGODB_URL: mongodb://root:Abc123@mongo:27017/ #set


#docker-compose -f mongo-composer.yml up